# Generated by Django 3.0.1 on 2024-03-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20240306_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imageAuthor',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
    ]
