# Generated by Django 3.0.1 on 2024-03-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_categoryblog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BaiViet',
        ),
    ]
