# Generated by Django 3.0.1 on 2024-03-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20240307_0305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaiViet',
            new_name='Blog',
        ),
    ]
